import 'app_settings.dart';

class AppLocalizations {
  static final Map<String, Map<String, String>> _localizedValues = {
    'vi': {
      'app_title': 'Ứng Dụng Vẽ & Tô Màu',
      'tasks_title': 'Nhiệm Vụ Vẽ & Tô Màu',
      'completed': 'Hoàn thành',
      'free_drawing': 'Vẽ Tự Do',
      'free_drawing_desc': 'Thỏa sức sáng tạo với bảng vẽ trống',
      'color_circle': 'Tô Màu Hình Tròn',
      'color_circle_desc': 'Tô màu cho hình tròn',
      'color_square': 'Tô Màu Hình Vuông',
      'color_square_desc': 'Tô màu cho hình vuông',
      'color_star': 'Tô Màu Ngôi Sao',
      'color_star_desc': 'Tô màu cho ngôi sao',
      'color_heart': 'Tô Màu Trái Tim',
      'color_heart_desc': 'Tô màu cho trái tim',
      'color_house': 'Tô Màu Ngôi Nhà',
      'color_house_desc': 'Tô màu cho ngôi nhà',
      'rainbow': 'Vẽ Cầu Vồng',
      'rainbow_desc': 'Vẽ cầu vồng 7 sắc màu',
      'pen': 'Bút',
      'eraser': 'Tẩy',
      'thickness': 'Độ dày:',
      'time_up': 'Hết giờ!',
      'time_up_msg': 'Thời gian 5 phút đã hết!\n\nBạn có muốn tiếp tục vẽ hay hoàn thành nhiệm vụ?',
      'back': 'Quay lại',
      'add_5_min': 'Thêm 5 phút',
      'complete': 'Hoàn thành',
      'task_completed': 'Hoàn thành nhiệm vụ!',
      'score': 'Điểm',
      'excellent': 'Xuất sắc! Bạn đã hoàn thành nhiệm vụ với thời gian còn lại:',
      'good_job': 'Bạn đã hoàn thành nhiệm vụ này!\nHãy thử thách mình với thời gian ngắn hơn lần sau!',
      'user_profile': 'Thông Tin Người Dùng',
      'tasks_completed': 'Hoàn thành',
      'avg_score': 'Điểm TB',
      'rank': 'Xếp hạng',
      'edit_profile': 'Chỉnh sửa hồ sơ',
      'notifications': 'Thông báo',
      'language': 'Ngôn ngữ',
      'theme': 'Giao diện',
      'history': 'Lịch Sử Hoàn Thành',
      'no_history': 'Chưa có nhiệm vụ nào được hoàn thành',
      'completed_at': 'Hoàn thành:',
      'ok': 'OK',
      'save': 'Lưu',
      'edit': 'Sửa',
      'vietnamese': 'Tiếng Việt',
      'english': 'Tiếng Anh',
      'light_mode': 'Chế độ sáng',
      'dark_mode': 'Chế độ tối',
      'system_mode': 'Theo hệ thống',
      'tasks': 'Nhiệm vụ',
      'my_profile': 'Dòng tin của tôi',
      'news': 'Tin tức',
      'new_tasks': 'Nhiệm vụ mới',
      'rewards': 'Phần thưởng',
      'congratulations': 'Chúc mừng!',
      'reward_msg': 'Bạn đã nhận được phần thưởng khi hoàn thành nhiệm vụ:',
      'points': 'điểm',
      'management': 'Quản lý',
      'admin': 'Quản trị',
      'users': 'Người dùng',
      'user_list': 'Danh sách user',
      'total_users': 'Người dùng',
      'total_tasks': 'Nhiệm vụ',
      'total_completed': 'Lượt hoàn thành',
      'shapes': 'Hình dạng',
      'manage_shapes': 'Quản lý shapes',
      'reports': 'Báo cáo',
      'statistics': 'Thống kê chi tiết',
      'add_edit_delete': 'Thêm, sửa, xóa',
      'face_login': 'Đăng nhập bằng khuôn mặt',
      'face_registered': 'Đã đăng ký khuôn mặt',
      'face_not_registered': 'Chưa đăng ký khuôn mặt',
      'register_face': 'Đăng ký khuôn mặt',
      're_register': 'Đăng ký lại',
      'allow_face_login': 'Cho phép đăng nhập',
      'total_accounts': 'Tổng tài khoản',
      'users_management': 'Người dùng',
      'history_drawings': 'Lịch sử & tranh vẽ',
      'logout': 'Đăng xuất',
      'confirm_logout': 'Xác nhận đăng xuất',
      'confirm_logout_msg': 'Bạn có chắc chắn muốn đăng xuất?',
      'cancel': 'Hủy',
      'review_drawings': 'Xem lại các tranh bạn đã vẽ',
      'leaderboard': 'Bảng Xếp Hạng',
      'top_10': 'TOP 10 người chơi xuất sắc nhất',
      'recent_completions': 'Hoàn thành gần đây',
      'complete_tasks_reward': 'Hoàn thành nhiệm vụ để nhận phần thưởng!',
      'loading_tasks': 'Đang tải nhiệm vụ...',
      'birth_date': 'Ngày sinh: ',
      'select_birth_date': 'Chọn ngày sinh',
      'gender': 'Giới tính: ',
      'male': 'Nam',
      'female': 'Nữ',
      'other': 'Khác',
      'no_drawing': 'Không có hình vẽ',
      'time': 'Thời gian',
      'no_leaderboard_data': 'Chưa có dữ liệu xếp hạng',
      'initializing_camera': 'Đang khởi tạo camera...',
      'no_camera': 'Không tìm thấy camera',
      'look_at_camera': 'Hãy nhìn vào camera',
      'camera_error': 'Lỗi khởi tạo camera',
      'scanning_face': 'Đang quét... ',
      'multiple_faces': 'Phát hiện nhiều khuôn mặt! Chỉ 1 người',
      'no_face_detected': 'Không phát hiện khuôn mặt',
      'saving_face_data': 'Đang lưu dữ liệu khuôn mặt...',
      'face_enrollment_success': 'Đăng ký khuôn mặt thành công!',
      'face_login_ready': 'Bây giờ bạn có thể đăng nhập bằng khuôn mặt',
      'face_enrollment_error': 'Lỗi khi đăng ký khuôn mặt',
      'try_again': 'Hãy thử lại',
      'close': 'Đóng',
      'profile_updated': 'Đã lưu thông tin',
      'profile_update_error': 'Lỗi khi lưu thông tin',
    },
    'en': {
      'app_title': 'Drawing & Coloring App',
      'tasks_title': 'Drawing & Coloring Tasks',
      'completed': 'Completed',
      'free_drawing': 'Free Drawing',
      'free_drawing_desc': 'Let your creativity flow with a blank canvas',
      'color_circle': 'Color Circle',
      'color_circle_desc': 'Color the circle',
      'color_square': 'Color Square',
      'color_square_desc': 'Color the square',
      'color_star': 'Color Star',
      'color_star_desc': 'Color the star',
      'color_heart': 'Color Heart',
      'color_heart_desc': 'Color the heart',
      'color_house': 'Color House',
      'color_house_desc': 'Color the house',
      'rainbow': 'Draw Rainbow',
      'rainbow_desc': 'Draw a 7-color rainbow',
      'pen': 'Pen',
      'eraser': 'Eraser',
      'thickness': 'Thickness:',
      'time_up': 'Time\'s Up!',
      'time_up_msg': 'The 5-minute time limit has expired!\n\nDo you want to continue drawing or complete the task?',
      'back': 'Back',
      'add_5_min': 'Add 5 minutes',
      'complete': 'Complete',
      'task_completed': 'Task Completed!',
      'score': 'Score',
      'excellent': 'Excellent! You completed the task with time remaining:',
      'good_job': 'You completed this task!\nTry to challenge yourself with less time next time!',
      'user_profile': 'User Profile',
      'tasks_completed': 'Completed',
      'avg_score': 'Avg Score',
      'rank': 'Rank',
      'edit_profile': 'Edit Profile',
      'notifications': 'Notifications',
      'language': 'Language',
      'theme': 'Theme',
      'history': 'Completion History',
      'no_history': 'No tasks completed yet',
      'completed_at': 'Completed:',
      'ok': 'OK',
      'save': 'Save',
      'edit': 'Edit',
      'vietnamese': 'Vietnamese',
      'english': 'English',
      'light_mode': 'Light Mode',
      'dark_mode': 'Dark Mode',
      'system_mode': 'System Default',
      'tasks': 'Tasks',
      'my_profile': 'My Feed',
      'news': 'News',
      'new_tasks': 'New Tasks',
      'rewards': 'Rewards',
      'congratulations': 'Congratulations!',
      'reward_msg': 'You received a reward for completing the task:',
      'points': 'points',
      'management': 'Management',
      'admin': 'Admin',
      'users': 'Users',
      'user_list': 'User List',
      'total_users': 'Users',
      'total_tasks': 'Tasks',
      'total_completed': 'Completions',
      'shapes': 'Shapes',
      'manage_shapes': 'Manage Shapes',
      'reports': 'Reports',
      'statistics': 'Detailed Statistics',
      'add_edit_delete': 'Add, Edit, Delete',
      'face_login': 'Face Login',
      'face_registered': 'Face registered',
      'face_not_registered': 'Face not registered yet',
      'register_face': 'Register Face',
      're_register': 'Re-register',
      'allow_face_login': 'Allow face login',
      'total_accounts': 'Total Accounts',
      'users_management': 'Users',
      'history_drawings': 'History & drawings',
      'logout': 'Logout',
      'confirm_logout': 'Confirm Logout',
      'confirm_logout_msg': 'Are you sure you want to logout?',
      'cancel': 'Cancel',
      'review_drawings': 'Review your drawings',
      'leaderboard': 'Leaderboard',
      'top_10': 'TOP 10 best players',
      'recent_completions': 'Recent Completions',
      'complete_tasks_reward': 'Complete tasks to receive rewards!',
      'loading_tasks': 'Loading tasks...',
      'birth_date': 'Birth Date: ',
      'select_birth_date': 'Select Birth Date',
      'gender': 'Gender: ',
      'male': 'Male',
      'female': 'Female',
      'other': 'Other',
      'no_drawing': 'No drawing found',
      'time': 'Time',
      'no_leaderboard_data': 'No leaderboard data yet',
      'initializing_camera': 'Initializing camera...',
      'no_camera': 'Camera not found',
      'look_at_camera': 'Look at camera',
      'camera_error': 'Camera initialization error',
      'scanning_face': 'Scanning... ',
      'multiple_faces': 'Multiple faces detected! Only one person allowed',
      'no_face_detected': 'No face detected',
      'saving_face_data': 'Saving face data...',
      'face_enrollment_success': 'Face enrollment successful!',
      'face_login_ready': 'You can now login with face recognition',
      'face_enrollment_error': 'Face enrollment failed',
      'try_again': 'Try again',
      'close': 'Close',
      'profile_updated': 'Profile updated',
      'profile_update_error': 'Error updating profile',
    },
  };

  static String translate(String key) {
    return _localizedValues[AppSettings.language]?[key] ?? key;
  }

  static String get(String key) => translate(key);
}

